[package]
name = "raytracer"
version = "1.1.0"
authors = ["Chiyu Hao"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
indicatif = "0.17.7"
imageproc = "0.23.0"
rand = "0.8.5"
rayon = "1.8.0"
